import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "fra-cream": "#F5F2EA",
        "fra-cream-card": "#FAF8F3",
        "fra-yellow": "#FFE600",
        "fra-yellow-hover": "#edd600",
        "fra-black": "#000000",
        "fra-sidebar": "#0A0A0A",
        "fra-sidebar-card": "#141414",
        "fra-border": "#000000",
        "fra-gray": "#E5DFD3",
        "fra-green": "#22C55E",
        "fra-amber": "#F59E0B",
        "fra-red": "#EF4444",
        "surface-bright": "#faf7f2",
        "on-primary-container": "#1a1a1a",
        "on-background": "#1a1a1a",
        "primary-fixed-dim": "#e6b800",
        "surface-container-highest": "#e2ddd4",
        "error": "#cc0000",
        "on-primary": "#ffffff",
        "tertiary": "#0055ff",
        "inverse-primary": "#f5f0e8",
        "primary-container": "#ffcc00",
        "on-tertiary-fixed": "#1a1a1a",
        "on-error-container": "#93000a",
        "surface-dim": "#d6d1c9",
        "secondary": "#e63b2e",
        "surface-tint": "#1a1a1a",
        "surface-variant": "#e8e3da",
        "on-tertiary-container": "#1a1a1a",
        "on-secondary": "#1a1a1a",
        "secondary-container": "#ffdad6",
        "on-primary-fixed": "#1a1a1a",
        "on-tertiary": "#ffffff",
        "outline-variant": "#d0cbc3",
        "on-secondary-fixed": "#1a1a1a",
        "background": "#f5f0e8",
        "on-surface": "#1a1a1a",
        "on-surface-variant": "#4a4a4a",
        "inverse-surface": "#1a1a1a",
        "on-secondary-container": "#1a1a1a",
        "tertiary-fixed-dim": "#a8c6ff",
        "surface-container": "#eee9e0",
        "on-primary-fixed-variant": "#1a1a1a",
        "secondary-fixed": "#ffdad6",
        "primary-fixed": "#ffcc00",
        "primary": "#1a1a1a",
        "surface-container-high": "#e8e3da",
        "secondary-fixed-dim": "#ffb3ab",
        "inverse-on-surface": "#f5f0e8",
        "tertiary-fixed": "#d6e3ff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#1a1a1a",
        "surface-container-low": "#f2ede5",
        "surface": "#f5f0e8",
        "on-tertiary-fixed-variant": "#1a1a1a",
        "tertiary-container": "#d6e3ff",
        "surface-container-lowest": "#ffffff",
        "outline": "#1a1a1a",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        sans: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        headline: ["Space Grotesk"],
        display: ["Space Grotesk"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk"]
      },
      boxShadow: {
        'brutal': '2px 2px 0px #000000',
        'brutal-sm': '1.5px 1.5px 0px #000000',
        'brutal-lg': '4px 4px 0px #000000',
      },
    }
  },
  plugins: [],
};
export default config;
